### ISSUE TITLE
TIME_ONE variable not working

### ISSUE THREAD

**Issue by vern3851** [willswire/balena-dashboards#11]
Hi Team
Setting TIME_ONE seems to be getting ignored and URLs play continuesly, same with and override TIME_ONE Vs global.
v8.0.2

**Comment by willswire** [comment]
@vern3851 thank you for your feedback! Can you try rephrasing the issue? I'm having a little bit of trouble understanding what exactly the problem is.

**Comment by vern3851** [comment]
Hi @willswire 
So in really simple terms the goal here is to have our fleet of rPis watching a website and periodically refreshing that website, F5 in a traditional browser.
Im sure this worked back in 2.1.1 when the variable was TIME_1

**Comment by willswire** [comment]
I can confirm that a custom time interval for `TIME_ONE` works.  Have you also properly set the variable `URL_ONE`?  Can you take a screenshot of the device's environment variables page from the balenaCloud control panel?

**Comment by vern3851** [comment]
![2020-02-19_13-37-53](https://user-images.githubusercontent.com/48300257/74796660-5c8b2000-531d-11ea-9695-2482325ca06e.jpg)

**Comment by willswire** [comment]
Trying [purging the data](https://www.balena.io/docs/learn/manage/actions/#purge-data) and see if that corrects the issue.  Sometimes this has helped with errors on my end.

**Comment by vern3851** [comment]
Hi @willswire 
Unfortunantly nope purging data didnt help.
However i think ive found a work-around.
Its looking like perhaps the TIME variable is only aknowledged when more that one URL is defined.
So i've made a URL_TWO and a TIME_TWO with the same variables as my ONE entries.
I now see in the logs:
`24.02.20 13:20:29 (+1100)  electron  Showing slide 1 of 2 for 3600 seconds`
I dont recall ever seeing a "showing slide 1 of 1 for x seconds" before adding the TWO variables.

Have deployed to one of our devices to test.

**Comment by vern3851** [comment]
hmmm this seems to now just be switching between what feels like two browser tabs rather than switching and hitting F5, this is probably good for users who have to enter creds on each URL, but its not working for us.
Any ideas how to get it to refresh periodically?

**Comment by willswire** [comment]
@vern3851 that means it is working correctly!  The window is in fact refreshing in the background.

The code works like this:

URL_ONE
URL_TWO

1:  show URL_ONE for x seconds, load URL_TWO in the background
2:  hide URL_ONE, refresh URL_ONE AND show URL_TWO for x seconds
3:  hide URL_TWO, refresh URL_TWO AND show URL_ONE for x seconds
4.  etc....

**Comment by vern3851** [comment]
AHHH i see.
Sorry i was expecting the refresh on the show portion, Time will tell but i think this is behaving as we need it by running the same URL twice.
PS: Thanks for putting together such a perfect mix of basic, yet feature rich code.
:)
