### ISSUE TITLE
I have a problem with NoVNC service

### ISSUE THREAD

**Issue by chaso5** [willswire/balena-dashboards#12]
Hello
Currently I don't know how to use NoVNC service, the log has "http://e5024c4:80/vnc.html?Host= e5024c4&port=80" but I cannot access it. I also tried typing the IP address into a web browser but it didn't work either, please help me

**Comment by willswire** [comment]
@chaso5 you can access the NoVNC service through your internet browser by navigating to the public device url.  Balena has [documentation on their website](https://www.balena.io/docs/learn/manage/actions/#enable-public-device-url) on how to enable this feature

**Comment by willswire** [comment]
@chaso5 can you confirm that you have access to NoVNC using the public device URL option, as detailed above?
