### ISSUE TITLE
Possibility to add Device environment variables for zooming on a webpage

### ISSUE THREAD

**Issue by dionsamsoe** [willswire/balena-dashboards#15]
Hi,

Not really a issue but more a request if it is possible to program some lines which makes us able to add a variable to zoom in or out on a webpage.

Thanks in advance!

Dion

**Comment by willswire** [comment]
@dionsamsoe sorry for the _super late_ reply! This feature has actually been available for some time now, but it was not documented in the README. I just merged in the change ref commit #16
