### ISSUE TITLE
Black screen, display error in log

### ISSUE THREAD

**Issue by Floppy** [willswire/balena-dashboards#2]
Having followed the instructions in the README, I just get a black screen. The machine is OK, I've use balena-dash OK, but this app doesn't seem to work.

I suspect it's something to do with the following error in the log, but I'm not sure:

```
25.04.19 12:03:33 (+0100)  dashboard  xauth: (argv):1:  bad display name "f59629a:0" in "remove" command
```

Full log attached as well. Any suggestions greatly appreciated!

[dashboard_wispy-night-25.04.19_12_12_19_(+0100).txt](https://github.com/willswire/dashboards/files/3116617/dashboard_wispy-night-25.04.19_12_12_19_.%2B0100.txt)

**Comment by willswire** [comment]
Hey @Floppy! Thanks for reaching out.

Try the 'purge data' button in the balenacloud control panel.

Also, if you are unable to resolve the issue, it might help to provide me with some context about your physical connections, device, hardware etc.

**Comment by Floppy** [comment]
Hi @willswire, thanks! I did try that, and did a completely clean setup as well, to no avail. It's on a raspberry pi 3 on ethernet, currently, and as I say other things work OK. I'll have another crack at it over the weekend, see if I can find out any more.

**Comment by willswire** [comment]
Made a few changes to the repo. Do a fresh clone/download and push using the balena-cli tool and let me know if you have any success!

**Comment by Floppy** [comment]
No difference unfortunately. I'll keep digging.

**Comment by willswire** [comment]
Make sure your ENV variables are matching this type of format.  Try starting with one screen and one time value.

![screenshot](https://user-images.githubusercontent.com/36860545/57019189-c2be7f00-6bf3-11e9-993b-36f88c10db09.png)

**Comment by willswire** [comment]
Re-pushed the repo to my own devices and found that the builder was pulling in a newer version of Electron (v5).  Had to include the --no-sandbox flag on line 39 of the start.sh file.

**Comment by willswire** [comment]
If you could confirm that this new update fixes your issue, that would be great!

**Comment by Floppy** [comment]
It works! Well done finding that, and thanks :D
