### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Floppy** [willswire/balena-dashboards#3]
Have you tried to set up the app with persistent authentication for some web pages? We want to display Google Datastudio reports, but obviously they're sensitive so the viewer needs to be logged in. I think I tried this a while back, and got it logged in, but then when the device restarts it loses the auth. Any ideas how we might do this?

/cc @gisleburt @paddyalton

**Comment by willswire** [comment]
There's a major release incoming (today) which should allow for this option.  Rather than load x number of URLs in one browserWindow, the program will load x number of browserWindows -- allowing for persistent auth for pages which are locked-down.

**Comment by Floppy** [comment]
Ooh, exciting! Thanks for the update :)

**Comment by willswire** [comment]
@Floppy Check to see if the new release fixes your issue!
