### ISSUE TITLE
Web pages authentication

### ISSUE THREAD

**Issue by enricobertoldi** [willswire/balena-dashboards#4]
Hi,
great project!

The credentials (username and password) of a website are not saved after restarting the raspberry pi.
I saw that another user had already reported this problem, but it seems to have not yet been resolved.

Do you think there is any way to fix it?

Thank you :)

**Comment by willswire** [comment]
Good Afternoon!

Thanks!

Nothing is stored for security restarts between reboots.  I did just update the project so that a singular page will stay open forever, without requiring a refresh. Does that help your situation at all?

**Comment by enricobertoldi** [comment]
I thank you for the effort but I needed to save the credentials even after
the restart

Ty bro

Il gio 7 nov 2019, 22:18 William Walker <notifications@github.com> ha
scritto:
