### ISSUE TITLE
A white screen flickers when switching dashboards - improvement idea

### ISSUE THREAD

**Issue by rudam** [willswire/balena-dashboards#8]
Hi.
We use a dark schema in Grafana, so the white screen flickering during switching the dashboards (~1/2 sec.) is disturbing people in the office. If there is any chance to improve this behaviour we will be so happy.

Thanks,
M.

**Comment by willswire** [comment]
@rudam this is probably a limitation from your hardware.  Recent updates to electron, and this project, have fixed those issues.  I'd suggest upgrading to a Raspberry Pi 3B+

**Comment by rudam** [comment]
Thanks. I will do the upgrade and will report results. Must wait for the fix from Electron guys, currently on v6.

**Comment by willswire** [comment]
Sounds good!

**Comment by roinone** [comment]
I see this as well on my Pi 3B+.  I haven't tried upping to v7 because of #7 -- so, it seems like the current holdup is the v7 fixes needed?
