### ISSUE TITLE
Setting of TIMEZONE - improvement

### ISSUE THREAD

**Issue by rudam** [willswire/balena-dashboards#9]
I want to ask for instructions or improvement if needed to be able to set the local timezone for the Electron container.
Thanks.

**Comment by willswire** [comment]
This option is already available by setting an environment variable! :)

`TZ`   `America/New_York`

<img width="962" alt="Screen Shot 2019-11-11 at 3 19 41 PM" src="https://user-images.githubusercontent.com/36860545/68618132-b1093e80-0496-11ea-948d-6d357ca72842.png">

For a full list of supported timezones, see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by rudam** [comment]
Nice, thank you! Just mention it in the README, please.

**Comment by willswire** [comment]
Updated!
